BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS balance (
    user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    balance NUMERIC(10, 2) DEFAULT 0,
    debited NUMERIC(10, 2) DEFAULT 0
);

COMMIT;