services:
  loyalty:
    container_name: go-advaced-gophermart-loyalty
    build: 
      context: ./deploy/local
    depends_on:
      - gophermart-db
      - accrual
    volumes:
      - .:/usr/local/src
      # - ${HOME}:${HOME}:rw
      # - /etc/passwd:/etc/passwd:ro
      # - /etc/group:/etc/group:ro
      # - /etc/shadow:/etc/shadow:ro
    # user: 1000:1000
    environment:
      RUN_ADDRESS: :8080
      DATABASE_URI: postgres://gophermart:gophermart@gophermart-db:5432/loyalty?sslmode=disable
      ACCRUAL_SYSTEM_ADDRESS: http://accrual:8080
      JWT_SECRET: SecretPhrase
    ports:
      - 8080:8080
    networks:
      - gophermart
    command: go run cmd/gophermart/main.go

  accrual:
    container_name: go-advaced-gophermart-accrual
    image: ubuntu:24.04
    environment:
      RUN_ADDRESS: :8080
      DATABASE_URI: postgres://gophermart:gophermart@gophermart-db:5432/accrual?sslmode=disable
    ports:
      - 8090:8080
    networks:
      - gophermart
    depends_on:
      - gophermart-db
    volumes:
      - ./cmd/accrual:/usr/local/bin
    command: ["accrual_linux_amd64"]

  gophermart-db:
      container_name: go-advaced-gophermart-postgres-db
      image: postgres:17.2
      working_dir: /app
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U gophermart -d accrual" ]
        interval: 10s
        retries: 5
        start_period: 30s
        timeout: 10s
      environment:
        POSTGRES_USER: postgres
        POSTGRES_DB: postgres
        POSTGRES_PASSWORD: "P@ssw0rd"
        PGDATA: "/var/lib/postgresql/data"
      ports:
          - '5432:5432'
      networks:
          - gophermart
      volumes:
          - "./db/init:/docker-entrypoint-initdb.d"
          - gophermart-pgdata:/var/lib/postgresql/data
      restart: always

networks:
  gophermart:
      name: gophermart
      driver: bridge

volumes:
  gophermart-pgdata: